#!/usr/bin/env python3
"""Convert Tux Racer sound effects (16-bit stereo 44.1 kHz WAV) into
8-bit signed mono samples at ~11 kHz for the 32X PWM synthesizer.

Output: src/gen/sounds.c with one const s8 array per sound and a table.
Sounds are GPLv2 (tuxracer-data-0.61/sounds).
"""
import os, struct, wave

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.environ.get('TUXRACER_DATA', '/home/user/ref/tuxracer-data-0.61')
OUT = os.path.join(ROOT, 'src', 'gen', 'sounds.c')
TARGET_RATE = 11025

SOUNDS = [
    ('fish_pickup1', 'fish_pickup1.wav', 0.6),
    ('tux_hit_tree1', 'tux_hit_tree1.wav', 1.0),
    ('tux_on_snow1', 'tux_on_snow1.wav', 1.2),
    ('tux_on_ice1', 'tux_on_ice1.wav', 1.2),
    ('tux_on_rock1', 'tux_on_rock1.wav', 1.2),
]

def load(path, max_seconds):
    w = wave.open(path, 'rb')
    ch, sw, rate, n = w.getnchannels(), w.getsampwidth(), w.getframerate(), w.getnframes()
    frames = w.readframes(n)
    w.close()
    assert sw == 2
    data = struct.unpack('<%dh' % (n * ch), frames)
    mono = [sum(data[i * ch:(i + 1) * ch]) / ch for i in range(n)]
    n = min(n, int(max_seconds * rate))
    mono = mono[:n]
    # resample with box filter
    step = rate / TARGET_RATE
    out = []
    pos = 0.0
    while pos + step <= n:
        a, b = int(pos), int(pos + step)
        seg = mono[a:b] or [mono[a]]
        out.append(sum(seg) / len(seg))
        pos += step
    peak = max(1.0, max(abs(v) for v in out))
    gain = 32767.0 / peak
    return [max(-127, min(127, int(round(v * gain / 258.0)))) for v in out], rate

def main():
    lines = ['/* Generated by tools/convert_sounds.py from tuxracer-data-0.61/sounds (GPLv2). Do not edit. */',
             '#include "../core/fixed.h"', '#include "../platform/32x/sound.h"', '']
    table = []
    for name, fname, max_s in SOUNDS:
        samples, rate = load(os.path.join(DATA, 'sounds', fname), max_s)
        lines.append('static const s8 snd_%s[%d] = {' % (name, len(samples)))
        for i in range(0, len(samples), 32):
            lines.append('    ' + ','.join(str(v) for v in samples[i:i + 32]) + ',')
        lines.append('};')
        table.append('    { snd_%s, %d },' % (name, len(samples)))
        print('%-16s %6d samples (%.2f s)' % (name, len(samples), len(samples) / TARGET_RATE))
    lines.append('const sound_def_t sound_defs[%d] = {' % len(SOUNDS))
    lines.extend(table)
    lines.append('};')
    lines.append('const int num_sound_defs = %d;' % len(SOUNDS))
    with open(OUT, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print('wrote', OUT)

if __name__ == '__main__':
    main()
