#!/usr/bin/env python3
"""Render an 8x8 bitmap font (ASCII 32..127) from DejaVu Sans Mono Bold."""
import os
from PIL import Image, ImageDraw, ImageFont

OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'core', 'font8.h')
CANDIDATES = [
    '/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf',
    '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf',
]

def main():
    font = None
    for c in CANDIDATES:
        if os.path.exists(c):
            font = ImageFont.truetype(c, 11)
            break
    if font is None:
        font = ImageFont.load_default()
    rows = []
    for ch in range(32, 128):
        im = Image.new('L', (8, 8), 0)
        d = ImageDraw.Draw(im)
        d.text((0, -3), chr(ch), fill=255, font=font)
        px = im.load()
        glyph = []
        for y in range(8):
            b = 0
            for x in range(8):
                if px[x, y] > 110:
                    b |= 1 << (7 - x)
            glyph.append(b)
        rows.append(glyph)
    with open(OUT, 'w') as f:
        f.write('/* Generated by tools/gen_font.py (DejaVu Sans Mono, Bitstream Vera licence). */\n')
        f.write('#ifndef FONT8_H\n#define FONT8_H\n')
        f.write('static const unsigned char font8[96][8] = {\n')
        for i, g in enumerate(rows):
            f.write('    {' + ','.join('0x%02x' % b for b in g) + '}, /* %s */\n' % (chr(32 + i) if 32 + i != 127 else 'DEL'))
        f.write('};\n#endif\n')
    print('wrote', OUT)

if __name__ == '__main__':
    main()
