#!/usr/bin/env python3
"""Generate fixed-point math tables for the Tux Racer 32X port.

Outputs src/gen/tables.c:
  fx_sintab[4096]      sin(2*pi*i/4096) in 16.16
  fx_asintab[257]      asin(i/256) in 16.16 degrees
  drag_force_tab[257]  air drag force (N, 16.16) for speed = i*0.5 m/s,
                       computed with Tux Racer's exact wind-force formula
                       (phys_sim.c calc_wind_force, no wind).
  fx_rsqrt_tab[64]     1/sqrt(x) for x in [1,4) (16.16) - fast normalise
"""
import math, os, sys

OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'gen', 'tables.c')

def fx(v):
    return int(round(v * 65536.0))

# ---- Tux Racer constants (phys_sim.c) ------------------------------------
TUX_WIDTH = 0.45
TUX_DIAMETER = TUX_WIDTH
AIR_DENSITY = 1.308
AIR_VISCOSITY = 17.00e-6
air_log_re = [-1, 0, 1, 2, 3, 4, 5, 6]
air_log_drag_coeff = [2.25, 1.35, 0.6, 0.0, -0.35, -0.45, -0.33, -0.9]

def lin_interp(x_vals, y_vals, x):
    n = len(x_vals)
    if x < x_vals[0]:
        i = 0
    elif x >= x_vals[-1]:
        i = n - 2
    else:
        i = 0
        while not (x_vals[i] <= x < x_vals[i + 1]):
            i += 1
    m = (y_vals[i + 1] - y_vals[i]) / (x_vals[i + 1] - x_vals[i])
    return y_vals[i] + m * (x - x_vals[i])

def drag_force(speed):
    if speed <= 0.0:
        return 0.0
    re = AIR_DENSITY * speed * TUX_DIAMETER / AIR_VISCOSITY
    cd = 10.0 ** lin_interp(air_log_re, air_log_drag_coeff, math.log10(re))
    return 0.5 * cd * AIR_DENSITY * speed * speed * (math.pi * TUX_DIAMETER * TUX_DIAMETER * 0.25)

def emit_array(f, ctype, name, vals, per_line=8, fmt='%d'):
    f.write('const %s %s[%d] = {\n' % (ctype, name, len(vals)))
    for i in range(0, len(vals), per_line):
        f.write('    ' + ', '.join(fmt % v for v in vals[i:i + per_line]) + ',\n')
    f.write('};\n\n')

def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        f.write('/* Generated by tools/gen_tables.py - do not edit. */\n')
        f.write('#include "../core/fixed.h"\n\n')
        emit_array(f, 'fx', 'fx_sintab', [fx(math.sin(2 * math.pi * i / 4096.0)) for i in range(4096)])
        emit_array(f, 'fx', 'fx_asintab', [fx(math.degrees(math.asin(min(1.0, i / 256.0)))) for i in range(257)])
        emit_array(f, 'fx', 'drag_force_tab', [fx(min(30000.0, drag_force(i * 0.5))) for i in range(257)])
        emit_array(f, 'fx', 'fx_rsqrt_tab', [fx(1.0 / math.sqrt(1.0 + (i + 0.5) * 3.0 / 64.0)) for i in range(64)])
        # 1/sqrt fine table over [1,2) for better precision: 256 entries
        emit_array(f, 'fx', 'fx_rsqrt_tab256', [fx(1.0 / math.sqrt(1.0 + (i + 0.5) / 256.0)) for i in range(256)])
        emit_array(f, 'fx', 'fx_sqrt_tab256', [fx(math.sqrt(1.0 + (i + 0.5) / 256.0)) for i in range(256)])
        emit_array(f, 'fx', 'fx_expneg_tab', [fx(math.exp(-i / 16.0)) for i in range(129)])
        # ny = sqrt(1 - q/127^2) for q = nx^2 + nz^2 (s8 normals), indexed by q >> 7
        # slope reciprocals for the rasteriser: recip_tab[d] = round(2^30 / d), d = 1..1023
        # (dx * recip_tab[dy]) >> 30 gives the 16.16 slope with a 64-bit product.
        emit_array(f, 'fx', 'recip30_tab', [0] + [int(round((1 << 30) / d)) for d in range(1, 1024)])
        # perspective: proj_tab[k] = round(FOCAL * 2^16 / (k / 32)) for camera z = k/32 m (k >= 8, z >= 0.25),
        # 16.16 result = FOCAL/z; screen = (coord * proj) >> 16.  z >= 128 m clamps to the last entry.
        emit_array(f, 'fx', 'proj_tab', [int(round(194.0 * 65536.0 * 32.0 / max(k, 8))) for k in range(4096)])
        emit_array(f, 'fx', 'nml_y_tab', [fx(math.sqrt(max(0.0, 1.0 - (i * 128 + 64) / 16129.0))) for i in range(127)])
    print('wrote', OUT)

if __name__ == '__main__':
    main()
